// <auto-generated />
namespace DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bancousu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bancousu));
        
        string IMigrationMetadata.Id
        {
            get { return "201703201246116_bancousu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
